# Fortigate Jinja2 Template Configuration File
#

# CORESNIPPETS
#
# This selects whichs snippets will be used
# If something is not needed just delete it 
coresnippets:
    - ipsec

#Variables
#Adjust variables as needed
#Don't edit the variable names, or stuff will break
hostname: &hostname fwl-001
wan: &wan wan1

#Automatic IPSec Config
#Tunnel Settings are automatically given!!
#if you need more flexibility use ipsec-custom (to be implemented)
#Carefull, policy generation is not finished, always check policies
ipsec:
    UMB_SDMZ:
        peer: 192.178.23.45
        psk: thisissosecurekeyhaha
        #Don't edit variable here, they're up up up!^
        port: *wan
        internal: internal
        local:
            - 10.10.229.0/24
            - 10.10.129.0/24
        remote:
            - 192.168.100.224/27
            - 192.168.100.224/27
    PartnerVPN:
        peer: 10.1.2.9
        psk: evenmoresecure!!!
        #Don't edit variable here, they're up up up!^
        port: *wan
        internal: internal
        local:
            - 10.10.229.0/24
            - 10.10.129.0/24
        remote:
            - 192.168.2.0/24
            - 192.168.2.0/24